### ISSUE TITLE
Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by maphew** [ahmeturun/GitExtensions.GitLab#4]
## Current behaviour

* Installed GitLab extension
* restarted Git Extensions
* open a repo folder on disk that had been cloned two years ago by other means from an on-premise GitLab server
* Git Extensions Error Report dialog shows up with the content below

## Expected behaviour

That I'd be able to use Git Extensions normally.

## Steps to reproduce

* open a repo folder on disk that had been cloned a year ago by other means from an on-premise GitLab server
* Git Extensions Error Report dialog shows up with the content below
* Dismissing the error dialog lets me use Git Extensions, within limits I'll describe later.

## Error Details
```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at RestSharp.RestClient..ctor(String baseUrl)
   at GitExtensions.GitLab.Client.Client..ctor(String gitLabDomain, String oAuthToken)
   at GitExtensions.GitLab.GitLabPlugin.InitializeConfiguredParameters(IGitModule gitModule)
   at GitExtensions.GitLab.GitLabPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.Dashboard.OnModuleChanged(Object sender, GitModuleEventArgs e)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.OnModuleChanged(GitModuleEventArgs args)
   at GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.listView1_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at GitUI.UserControls.ExListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by maphew** [comment]
Further experimentation reveals that Push fails with _"fatal: protocol error: bad line length character: git@"._ So there's something wrong with the origin's remote configuration.  The _origin_ url is `git@EXAMPLE.ca:env-devops/geo/ENV-GIS-COE.git`. 

The root problem is not GitLab plugin's fault, but the error handling might be improved so that the plugin reports the problem instead of crashing.

**Comment by maphew** [comment]
oh ffs.  See comment _"I simply forgot to load the private key in pageant what ended in fatal: protocol error: bad line length character: git@. What a misleading error message."_  on https://stackoverflow.com/questions/8170436/git-remote-error-fatal-protocol-error-bad-line-length-character-unab
